Try pr
cn/GB2260.py pull request #10
Opened 2017-06-28 04:28 UTC by yetihan

更换为最新数据源,修改了generate.py 和 makefile 文件

2017-06-28 07:32 UTC, tonyseek requested changes
Please clean up your `*_bak` files and squash your commits. The title and description of pull request need to be clear too. Thank you.

2017-06-28 07:32 UTC, tonyseek commented on gb2260/division.py
> -        return (int(year), 12)
What is the reason you change here for?

The structure of 2-tuple should be `(year, month)`. The default month should be `12` for solo-revised years.

2017-06-28 07:32 UTC, tonyseek commented on generate.py
> +
Extra spaces and empty lines need to be deleted

2017-06-28 09:05 UTC, yetihan commented on gb2260/division.py
> -        return (int(year), 12)
All filenames of new source data are like "yyyyMM". So,there is not need to turn 'yyyy' to (yyyy,mm). Maybe, we should change the vairable name of year

2017-06-28 10:00 UTC, yetihan commented on gb2260/division.py
> -        return (int(year), 12)
Hi,master.I have squash my commits. Is it ok this time ? ^_^

2017-06-28 10:09 UTC, tonyseek commented on gb2260/division.py
> -        return (int(year), 12)
IMO, we could not presume this except it is written down in [spec](https://github.com/cn/GB2260/blob/develop/spec.md).

2017-06-28 10:38 UTC, yetihan commented on gb2260/division.py
> -        return (int(year), 12)
See [spec](https://github.com/cn/GB2260/blob/develop/spec.md)
In the Data Structure part,"revision: (str) The revision year (month).",
Atfer all,i think it is more safe to reserve the code to deal year.

2017-06-29 00:03 UTC, yetihan commented on generate.py
> +
This problem has been resolved.

2017-07-03 10:17 UTC, yetihan commented on generate.py
> +
anything to do?

2021-08-12 03:51 UTC, closed without merging